# Generated by Django 3.0.3 on 2020-02-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.SlugField(blank=True, max_length=30, null=True)),
                ('tag2', models.SlugField(blank=True, max_length=30, null=True)),
                ('tag3', models.SlugField(blank=True, max_length=30, null=True)),
                ('tag4', models.SlugField(blank=True, max_length=30, null=True)),
                ('tag5', models.SlugField(blank=True, max_length=30, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
