# Generated by Django 3.0.3 on 2020-02-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200224_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag1',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('post', 'tag')},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag5',
        ),
    ]
