# Generated by Django 3.0.3 on 2020-02-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200225_1851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag',)},
        ),
    ]
