# Generated by Django 3.0.3 on 2020-02-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200221_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_user',
            new_name='category_creator',
        ),
    ]
