# Generated by Django 3.0.3 on 2020-02-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.CharField(blank=True, max_length=30, null=True)),
                ('tag2', models.CharField(blank=True, max_length=30, null=True)),
                ('tag3', models.CharField(blank=True, max_length=30, null=True)),
                ('tag4', models.CharField(blank=True, max_length=30, null=True)),
                ('tag5', models.CharField(blank=True, max_length=30, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
